### ISSUE TITLE
Ios index out of bounds error

### ISSUE THREAD

**Issue by pkurimella** [aquto/cordova-plugin-googleLogin#1]
i'm getting the following error when running this in the ios devices. Android works really well.

**\* WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSRangeException> **\* -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array

**Comment by jrunge** [comment]
hey, sorry for the confusion, I honestly didn't spend much time packaging this for public consumption.  You probably need to specify the bundle ID for the app in the [Google Developers Console](https://console.developers.google.com/) and then pass that in during plugin installation:

cordova plugin add https://github.com/aquto/cordova-plugin-googleLogin --variable PACKAGE_NAME=your.bundle.id

hope that helps
